#!/bin/bash
/usr/local/share/easy/skeleton.py -t /usr/local/share/easy/domain.conf.tpl --domain $2 > /usr/local/share/easy/domain.$2.conf
/usr/local/share/easy/skeleton.py \
  -t /usr/local/share/easy/domain.http.conf.tpl \
  --server_name $1 \
  --domain $2 \
  --location_path / \
  --location_target $3 \
  > /usr/local/share/easy/domain.http.$1.conf
